import type { DashboardPayload } from "./types";

const sellers = [
  { name: "Grandolini", contracts: 7, carOne: 1, adMotor: 6, appointments: 12 },
  { name: "Caironi", contracts: 2, carOne: 0, adMotor: 2, appointments: 17 },
  { name: "Liguori", contracts: 2, carOne: 0, adMotor: 2, appointments: 4 },
  { name: "Monacelli", contracts: 2, carOne: 1, adMotor: 1, appointments: 9 },
  { name: "Bordini", contracts: 2, carOne: 2, adMotor: 0, appointments: 5 },
];

export const snapshot: DashboardPayload = {
  source: "snapshot",
  lastUpdated: "2026-07-15T18:05:00+02:00",
  periods: {
    today: {
      label: "Oggi",
      subtitle: "Mercoledì 15 luglio · giornata in corso",
      leads: 29,
      appointments: 3,
      presented: 2,
      noShows: 0,
      pendingAppointments: 1,
      contracts: 0,
      carOneContracts: 0,
      adMotorContracts: 0,
      target: null,
      forecast: null,
      expectedToDate: null,
      remainingToTarget: null,
      requiredPerDay: null,
      sellers: [],
    },
    week: {
      label: "Settimana",
      subtitle: "S3 · 13–19 luglio",
      leads: 145,
      appointments: 15,
      presented: 8,
      noShows: 0,
      pendingAppointments: 7,
      contracts: 2,
      carOneContracts: 0,
      adMotorContracts: 2,
      target: 12,
      forecast: 5,
      expectedToDate: 5,
      remainingToTarget: 10,
      requiredPerDay: 2.5,
      sellers: [
        { name: "Grandolini", contracts: 1, carOne: 0, adMotor: 1, appointments: null },
        { name: "Caironi", contracts: 1, carOne: 0, adMotor: 1, appointments: null },
      ],
    },
    month: {
      label: "Mese & forecast",
      subtitle: "Luglio 2026 · dati al 15 luglio",
      leads: 800,
      appointments: 51,
      presented: 29,
      noShows: 13,
      pendingAppointments: 9,
      contracts: 15,
      carOneContracts: 4,
      adMotorContracts: 11,
      target: 50,
      forecast: 31,
      expectedToDate: 24,
      remainingToTarget: 35,
      requiredPerDay: 2.5,
      sellers,
    },
  },
  todayAgenda: [
    { id: "1", time: "11:30", seller: "Grandolini", status: "presented" },
    { id: "2", time: "17:00", seller: "Liguori", status: "presented" },
    { id: "3", time: "18:00", seller: "Caironi", status: "pending" },
  ],
  leadSources: [
    { name: "Facebook", leads: 551, appointments: null, contracts: null },
    { name: "Instagram", leads: 199, appointments: null, contracts: null },
    { name: "TikTok", leads: 50, appointments: null, contracts: null },
  ],
  sellerConversions: [
    { name: "Grandolini", appointments: 12, presented: 10, noShows: 2, pending: 0, contracts: 7 },
    { name: "Caironi", appointments: 17, presented: 7, noShows: 7, pending: 3, contracts: 2 },
    { name: "Liguori", appointments: 4, presented: 3, noShows: 0, pending: 1, contracts: 2 },
    { name: "Monacelli", appointments: 9, presented: 7, noShows: 1, pending: 1, contracts: 2 },
    { name: "Bordini", appointments: 5, presented: 2, noShows: 3, pending: 0, contracts: 2 },
  ],
  leadHistory: [],
  contractHistory: [],
};
