import type { DashboardPayload } from "./types";

const sellers = [
  { name: "Grandolini", contracts: 7, carOne: 1, adMotor: 6, appointments: 12 },
  { name: "Caironi", contracts: 2, carOne: 0, adMotor: 2, appointments: 17 },
  { name: "Liguori", contracts: 2, carOne: 0, adMotor: 2, appointments: 4 },
  { name: "Monacelli", contracts: 2, carOne: 1, adMotor: 1, appointments: 9 },
  { name: "Bordini", contracts: 2, carOne: 2, adMotor: 0, appointments: 5 },
];

export const snapshot: DashboardPayload = {
  source: "snapshot",
  lastUpdated: "2026-07-15T15:23:08+02:00",
  periods: {
    today: {
      label: "Oggi",
      subtitle: "Mercoledì 15 luglio · giornata in corso",
      leads: 22,
      appointments: 3,
      presented: 0,
      noShows: 0,
      pendingAppointments: 3,
      contracts: 0,
      carOneContracts: 0,
      adMotorContracts: 0,
      target: null,
      forecast: null,
      expectedToDate: null,
      remainingToTarget: null,
      requiredPerDay: null,
      sellers: [],
    },
    week: {
      label: "Settimana",
      subtitle: "S3 · 13–19 luglio",
      leads: 138,
      appointments: 14,
      presented: 6,
      noShows: 0,
      pendingAppointments: 8,
      contracts: 2,
      carOneContracts: 0,
      adMotorContracts: 2,
      target: 12,
      forecast: 5,
      expectedToDate: 5,
      remainingToTarget: 10,
      requiredPerDay: 2.5,
      sellers: [
        { name: "Grandolini", contracts: 1, carOne: 0, adMotor: 1, appointments: null },
        { name: "Caironi", contracts: 1, carOne: 0, adMotor: 1, appointments: null },
      ],
    },
    month: {
      label: "Mese & forecast",
      subtitle: "Luglio 2026 · dati al 15 luglio",
      leads: 793,
      appointments: 50,
      presented: 27,
      noShows: 13,
      pendingAppointments: 10,
      contracts: 15,
      carOneContracts: 4,
      adMotorContracts: 11,
      target: 50,
      forecast: 31,
      expectedToDate: 24,
      remainingToTarget: 35,
      requiredPerDay: 2.5,
      sellers,
    },
  },
  todayAgenda: [
    { id: "1", time: "11:30", seller: "Grandolini", status: "pending" },
    { id: "2", time: "17:00", seller: "Liguori", status: "pending" },
    { id: "3", time: "18:00", seller: "Caironi", status: "pending" },
  ],
};
